### ISSUE TITLE
API plan: MVP 0.5 tasks

### ISSUE THREAD

**Issue by BeckyPollard** [badgateway/tt-api#32]
### Let's get the app into a place where the basic user flow is successful!

The focus of "MVP 0.5" is all about getting the basic functions of the app's idea working, the user should be able to complete the user flow for the app. A user should be able to:
1. Log in or register.
2. Create & edit a client.
3. Create & edit a project.
4. Create & edit a user.
5. Log hours to a timesheet & edit entry.

## Tasks List
- [ ] App has login ability.
  - [ ] https://github.com/badgateway/tt-api/issues/13
  - [ ] https://github.com/badgateway/tt-api/issues/14
- [ ] Edit users.
  - [ ] https://github.com/badgateway/tt-api/issues/20
- [ ] Users can submit all their data to the API.

----

References:
➤ [Notion document](https://www.notion.so/Time-tracker-e2c07e71b55442e4a67de8c95fa90a00).
