### ISSUE TITLE
Investigate: Auth causing endless loop

### ISSUE THREAD

**Issue by syedfkabir** [badgateway/tt-api#44]
## Background 

- roulette auth problem
- the auth param on the login just cycles through `?code='blah'`s forever
- flashing authenticating screen after retrying auth, loops forever

![image](https://user-images.githubusercontent.com/31973147/197802899-aaa97815-e260-4419-affd-90ca9f64a721.png)

## Task

investigate the problem by doing the following

- [x] remove tt-api and tt-app, then add them back to a12n (use the links provided in the README.md to simulate a _automated_ experience) 
- [x] delete all relevant db entries for the time tracker, re-run knex scripts
- [x] empty local storage
- [ ] uninstall and reinstall a12n _(trying to avoid)_

**Comment by evert** [comment]
It might also be worthwhile just trying to empty localstorage

**Comment by syedfkabir** [comment]
After attempting a few strategies, 
I was successfully able to get the authentication piece working between the frontend and backend. 
I also confirmed that the changes work for another person as well. 
This task can be closed for now!
